### ISSUE TITLE
ERROR After Upgrade to Magento 2.2.3

### ISSUE THREAD

**Issue by josecoelho509** [PHOENIX-MEDIA/Magento2-CashOnDelivery#11] opened 2018-03-08 15:10 UTC
Hello

After updating from magento to 2.2.3, I stopped being able to add products to the cart.

I found the following error:

[08-Mar-2018 15:04:57 UTC] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Phoenix\CashOnDelivery\Model\Total\Tax\Quote::_clearValues() must be of the type array, object given, called in /.../app/code/Phoenix/CashOnDelivery/Model/Total/Tax/Quote.php on line 94 and defined in /...app/code/Phoenix/CashOnDelivery/Model/Total/Tax/Quote.php:119
Stack trace:
#0 /.../app/code/Phoenix/CashOnDelivery/Model/Total/Tax/Quote.php(94): Phoenix\CashOnDelivery\Model\Total\Tax\Quote->_clearValues(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\Quote\Address\Total), Object(Phoenix\CashOnDelivery\Model\Total\Tax\Quote))
#1 /.../vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): Phoenix\CashOnDelivery\Model\Total\Tax\Quote->collect(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#2 /.../vendor/magento/m in /home/momentco/public_html/magento/app/code/Phoenix/CashOnDelivery/Model/Total/Tax/Quote.php on line 119

Do you have a solution that can help me?

Thank you.

José Coelho

**Comment by PHOENIX-MEDIA** [comment] 2018-03-09 10:45
Duplicate of #8

**Closed as completed by PHOENIX-MEDIA** 2018-03-09 10:45 UTC
